name: queen_alerts
description: alert with simple and responsive alert ? or  toast ? or dialog ?
repository: https://github.com/maxzod/queen_alerts
homepage: https://github.com/maxzod/queen_alerts
issue_tracker: https://github.com/maxzod/queen_alerts/issues

version: 0.0.4-beta
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  pedantic: ^1.11.0
flutter:
  uses-material-design: true
